#!/usr/bin/env python

import subprocess
import sys

process = subprocess.Popen('%s src/main/scripts/pyb' % sys.executable, 
                           env={'PYTHONPATH': 'src/main/python'}, 
                           shell=True)
process.wait()                           

